In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(f"sqlite:///data/test.db")

In [4]:
pd.read_csv('data/test.csv')

,0,1,2,3,4,5,6,7,8,9,...,515335,515336,515337,515338,515339,515340,515341,515342,515343,515344
0,0.000000,1776.782648,656.868802,1907.786538,707.333745,697.219893,1519.485430,1787.170171,757.617157,4145.977080,...,8238.397243,849.399957,3857.478350,3555.643463,1331.387848,767.400080,1127.675348,4778.009045,3143.710112,859.165724
1,1776.782648,0.000000,1782.478850,1371.531336,1522.831777,1340.468128,1803.658506,1710.903994,1605.580446,4192.920276,...,7241.808160,1950.764554,3323.051667,3216.398644,1954.898339,1824.756054,1743.744775,5061.930032,2549.232420,2107.111223
2,656.868802,1782.478850,0.000000,1915.979731,817.158898,771.635327,1548.172129,1773.369820,860.622036,4025.863205,...,8146.270361,954.409474,3799.921829,3501.809308,1369.216801,831.983107,1088.840338,4590.345228,3017.852216,973.383203
3,1907.786538,1371.531336,1915.979731,0.000000,1613.856927,1601.557058,2160.857393,1771.905191,1778.725963,4364.587069,...,7148.669499,2084.830249,3206.054242,3275.881638,2101.739642,1977.596846,1854.137832,5044.950528,2335.427660,2197.782979
4,707.333745,1522.831777,817.158898,1613.856927,0.000000,638.708202,1742.627799,1831.318674,616.237483,4373.824709,...,8172.327481,981.708360,3861.360747,3671.372087,1451.843061,913.157090,1240.654230,5024.197787,3077.510459,1167.946006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,3581.276375,3357.696795,3558.182141,3624.815656,3788.201100,3520.095791,2613.373747,2834.554680,3870.205601,2108.855671,...,5893.269354,3808.404437,2286.620058,2657.900731,3172.281417,3556.395119,2976.481609,3633.284861,2596.044904,3494.623610
126,2189.878018,1653.255401,2246.203510,1948.260027,2255.401705,2006.710221,1686.712877,1795.482155,2366.541757,3310.186168,...,6374.584120,2442.552108,2553.258306,2369.759473,2165.028819,2209.050271,1950.897907,4182.416433,2179.926833,2251.733215
127,3282.979196,3217.849335,3260.099360,3564.248763,3576.880834,3290.147692,2321.849465,2531.949238,3668.029183,2155.539796,...,6233.124661,3584.670293,2796.953343,2167.050972,2991.431362,3377.984623,2873.520675,3277.198749,2867.209393,3151.438485
128,2506.852759,2155.779685,2510.670398,2396.932108,2648.336865,2378.934032,1832.376131,2026.973469,2765.530923,3057.541851,...,6313.450793,2756.949035,2518.390876,2378.042943,2392.472573,2537.220432,2239.256555,3929.136847,2305.541633,2570.462605
129,1939.652117,1716.171962,1937.029652,1742.333593,1968.757178,1758.069061,1542.804444,1677.767159,2018.312954,3385.202492,...,6817.456020,2140.124563,2410.116414,2993.935823,1854.930029,1878.712262,1438.868363,4518.582749,2137.734190,2076.056332